### ISSUE TITLE
Substitute env vars into config

### ISSUE THREAD

**Issue by ryardley** [gnosisguild/enclave#202]
In order to more effectively be able to configure our nodes we need to be able to substitute env vars in certain places within the config.

```yaml
address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
quic_port: 9094
enable_mdns: false
peers:
  - "${CN1_MULTIADDR}"
chains:
  - name: "${NETWORK}"
    rpc_url: "wss://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    contracts:
      enclave: "${ENCLAVE_ADDRESS}"
      ciphernode_registry: "${CIPHERNODE_REGISTRY_ADDRESS}"
      filter_registry: "0xcBaCE7C360b606bb554345b20884A28e41436934"

```

Currently we are using `Figment` which allows for magic env vars to be parsed and added to our config but these are not very flexible and are complex to document. An easier way for users will be for them to be able to supply env vars as above.
