### ISSUE TITLE
Create "swarm" mode derived from config.

### ISSUE THREAD

**Issue by ryardley** [gnosisguild/enclave#294]
In our integration test we currently have a complex setup to enable testing of a local mdns swarm: 

We launch each ciphernode independently:
https://github.com/gnosisguild/enclave/blob/main/tests/integration/base.sh#L35-L39

And define a complex set of separate configurations for each test node in the swarm:

- https://github.com/gnosisguild/enclave/blob/main/tests/integration/lib/cn1/config.yaml
- https://github.com/gnosisguild/enclave/blob/main/tests/integration/lib/cn2/config.yaml
- https://github.com/gnosisguild/enclave/blob/main/tests/integration/lib/cn3/config.yaml
- https://github.com/gnosisguild/enclave/blob/main/tests/integration/lib/cn4/config.yaml
- https://github.com/gnosisguild/enclave/blob/main/tests/integration/lib/ag/config.yaml

Instead of doing this we should consolidate these configs together to form a single config that declratively launches a set of mdns enabled nodes.

This should make it easier for local developers to test enclave.  

We can make a nodes section of the config. 

```yaml
# Note this is the top (normal) level
name: cn1
address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
quic_port: 9091
enable_mdns: true # mdns must be true or `enclave start` will fail because we are using the nodes key 

# The following are additional nodes that are spun up
nodes:
  cn2:
    address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
    quic_port: 9092
  cn3:
    address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
    quic_port: 9093
  cn4:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9094
  agg:
    address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9095
    template: "aggregator"
    
chains:
  - name: "hardhat"
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
```  

```yaml
# NOTE: as we are using `nodes` we need not specify a root node if we don't want to 
nodes:
  cn1:
    address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
    quic_port: 9091
  cn2:
    address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
    quic_port: 9092
  cn3:
    address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
    quic_port: 9093
  cn4:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9094
  agg:
    address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9095
    template: "aggregator"
    pubkey-write-path: "./output/pubkey.bin"
    plaintext-write-path: "./output/plaintext.txt"

chains:
  - name: "hardhat"
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
```  

This way `enclave start` should start the swarm. 

As the nodes start is should be clear from the console output that the nodes are starting in "swarm" mode.

**Comment by hmzakhalid** [comment]
Thanks @ryardley, this is a much-needed change. 
I like the config inheritance approach, top-level defaults overridden by node-specific values but I lean towards the second example you provided, where all nodes are explicitly defined under the nodes: key. It feels cleaner and less ambiguous than having some parameters define a 'main' node at the top level alongside the nodes: block.

maybe the final config structure would look something like this?
```yaml
# Top-level defaults apply to all nodes unless overridden
config_base_dir: . # Base for relative paths unless specified otherwise
data_base_dir: . # Nodes will get ./cn1/data, ./cn2/data etc. by default
enable_mdns: true # Default for nodes in this swarm config
chains:
  - name: "hardhat"
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"

# All nodes defined explicitly here
nodes:
  cn1:
    address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
    quic_port: 9091
    # Inherits chains, enable_mdns, default data_dir path pattern, etc.

  cn2:
    address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
    quic_port: 9092

  cn3:
    address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
    quic_port: 9093

  cn4:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9094
    # Example overriding data directory explicitly if needed
    # data_dir: /tmp/enclave_data_cn4

  agg:
    address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9095
    template: "aggregator"
    # Node-specific output paths
    pubkey-write-path: "./output/pubkey.bin" # Relative to config_base_dir? Needs definition.
    plaintext-write-path: "./output/plaintext.txt"
```

**Comment by ryardley** [comment]
Yeah I was tossing around with the same thoughts but now I realise you're right we don't need to care about backwards compatibility so simply having `nodes` makes sense and will be simpler and easier to implement too.

**Comment by ryardley** [comment]
@hmzakhalid seems to me we should possibly still have a root node configuration as a separate key as we need to support non mdns for `enclave start`

Just thinking about cli commands:

- `enclave dev evm` launch an anvil node 
- `enclave dev start` launch a swarm in development mode
- `enclave dev start --monitor` launch the node swarm with Jaeger UI for debugging / tracing
- `enclave dev` launch everything anvil, node swarm and jaeger

- `enclave start` launch a single production kademlia p2p node
- `enclave start --monitor --monitor.port 1234` launch a single production kademlia p2p node with colocated open telemetry collection for monitoring with UI

I can't really see a situation where we would want to run mdns connected nodes in production although in the future we could use that `nodes` config alongside kubernetes or something like that in a production situation. 

```yaml
# Top-level defaults apply to all nodes unless overridden
config_base_dir: . # Base for relative paths unless specified otherwise
data_base_dir: . # Nodes will get ./cn1/data, ./cn2/data etc. by default

node:
  chains:
    - name: "mainnet"
      rpc_url: "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
      contracts:
        enclave: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
        ciphernode_registry: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
        filter_registry: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  enable_mdns: false
  quic_port: 9091
  peers:
    - "/dns4/cn1.enclave.gg/udp/9091/quic-v1"
    - "/dns4/cn2.enclave.gg/udp/9092/quic-v1"
    - "/dns4/cn3.enclave.gg/udp/9093/quic-v1"
    - "/dns4/cn4.enclave.gg/udp/9094/quic-v1"

# All dev nodes defined explicitly here
dev:
  chains:
    - name: "hardhat"
      rpc_url: "ws://localhost:8545"
      contracts:
        enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
        ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
        filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
  enable_mdns: true # Default for nodes in this swarm config
  nodes:
    cn1:
      address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
      quic_port: 9091
      # Inherits chains, enable_mdns, default data_dir path pattern, etc.
  
    cn2:
      address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
      quic_port: 9092
  
    cn3:
      address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
      quic_port: 9093
  
    cn4:
      address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
      quic_port: 9094
      # Example overriding data directory explicitly if needed
      # data_dir: /tmp/enclave_data_cn4
  
    agg:
      address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
      quic_port: 9095
      template: "aggregator"
      # Node-specific output paths
      pubkey-write-path: "./output/pubkey.bin" # Relative to config_base_dir? Needs definition.
      plaintext-write-path: "./output/plaintext.txt"
```

**Comment by hmzakhalid** [comment]
Ah, okay, I see what you're getting at with needing distinct configurations.
On reflection, you're right, trying to merge them into one file but even with clever interpretation or nesting, probably adds more complexity than it saves. It'd be better to split the configs entirely – one file specifically for production/single-node setups, and a separate file for the development swarm.

Since the commands are different `enclave dev` & `enclave start` separating the files feels like the right way to move forward.
What do you think?

**Comment by ryardley** [comment]
I am not very keen on having multiple cli binaries because I think it adds complexity to the user experience and because of that i think we should try to have a single config for everything but make it flexible enough so that it can have a search priority and load from the local folder first followed by parent folders followed by users .config/enclave folder. 

I believe fragment might be able to support this. I stongly believe separate configs to be a mistake and i think it would be confusing. 

I am advocating for one key in the config to be for production and one for a test swarm.

**Comment by ryardley** [comment]
In terms of implementation my preference would be to do thread spawning and process management within rust as opposed to try and manage with an external script.

**Comment by ryardley** [comment]
Delivery of this task should be implemented in both the integration test and the examples/CRISP project. After implementation this should significantly reduce the code in the test. We will also need to work out how to target any one of the nodes and send commands to it (eg. kill yourself)

**Comment by ryardley** [comment]
This task requires managing process lifecycles for multiple enclave nodes so starting this task is predicate on #316

**Comment by ryardley** [comment]
So thinking through this some more trying to work through implementation and find a compromise with functionality. 

Problems:
- **shared config** each process needs to be driven from the same config file and differentiated by name
- **mdns** we can ditch mdns and make it so all the nodes automatically dial into each other using the peers list. 
- **writing chains to config** we can solve this by having a single `chains` key as above 
- **default node** which node should be the default node? 
- **redundant keys** there are going to be redundant keys in a config with a single node

**Comment by ryardley** [comment]
I am realizing designing this that this ticket is very much working towards this https://github.com/gnosisguild/enclave/issues/153

**Comment by ryardley** [comment]
Can we wrap a tool like systemd to manage this? Feels a little heavy handed would be good if there is a rust equiv we can embed.

**Comment by ryardley** [comment]
At this point the API looks good because it could theoretically be used to run both a local and distributed cluster

**Comment by ryardley** [comment]
`enclave start` should accept every single argument in a node's config tree. It should be the equivalent to `docker run` `enclave nodes` should be the equivalent to `docker compose`

**Comment by ryardley** [comment]
I am considering naming the command `enclave swarm` instead of `enclave nodes` the only downside is that the API is going to be closer to to `docker compose` in functionality but honestly no one remembers the docker swarm api anyway so maybe it is ok? 🤷🏾

**Comment by ryardley** [comment]
- [ ] `enclave swarm up --jaeger` 
  - [ ] starts up a status webserver for nodes to report to on port `15678` 
  - [ ] if `--jaeger` arg starts up a jaeger instance as an otel collector at `http://localhost:4317` accessible on `http://localhost:16686`
- [ ] `enclave start --status-server http://localhost:15678` sends a serialized struct to the status server containing the `peer_id`, `name`. Errors will be communicated by exiting with non zero code.

**Comment by ryardley** [comment]
This task may take longer than 2 days but not a week.

**Comment by ryardley** [comment]
We should do #325 as part of this

**Comment by ryardley** [comment]
```yaml
config_base_dir: . # will be the same as the config file by default
data_base_dir: . # Nodes will get ./cn1/data, ./cn2/data etc. by default

chains:
  mainnet:
    rpc_url: "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
    contracts:
      enclave: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
      ciphernode_registry: "0x1F98431c8aD98523631AE4a59f267346ea31F984"
      filter_registry: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  hardhat:
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"

node:
  quic_port: 9091
  peers:
    - "/dns4/cn1.enclave.gg/udp/9091/quic-v1"
    - "/dns4/cn2.enclave.gg/udp/9092/quic-v1"
    - "/dns4/cn3.enclave.gg/udp/9093/quic-v1"
    - "/dns4/cn4.enclave.gg/udp/9094/quic-v1"

nodes:
  cn1:
    address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
    quic_port: 9091

  cn2:
    address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
    quic_port: 9092

  cn3:
    address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
    quic_port: 9093

  cn4:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9094
    # Example overriding data directory explicitly if needed
    # data_dir: /tmp/enclave_data_cn4

  agg:
    address: "0x8626a6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9095
    template: "aggregator"
    # Node-specific output paths
    pubkey-write-path: "./output/pubkey.bin" # Relative to config_base_dir? Needs definition.
    plaintext-write-path: "./output/plaintext.txt"
```

**Comment by ryardley** [comment]
Settled on this config for our tests:

```yaml
config_dir: ./.enclave/config
data_dir: ./.enclave/data
chains:
  - name: "hardhat"
    rpc_url: "ws://localhost:8545"
    contracts:
      enclave: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      ciphernode_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
      filter_registry: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"

nodes:
  cn1:
    address: "0x2546BcD3c84621e976D8185a91A922aE77ECEc30"
    quic_port: 9091
    peers:
      - "/ip4/127.0.0.1/udp/9092/quic-v1"
      - "/ip4/127.0.0.1/udp/9093/quic-v1"
      - "/ip4/127.0.0.1/udp/9094/quic-v1"
      - "/ip4/127.0.0.1/udp/9095/quic-v1"
  cn2:
    address: "0xbDA5747bFD65F08deb54cb465eB87D40e51B197E"
    quic_port: 9092
    peers:
      - "/ip4/127.0.0.1/udp/9091/quic-v1"
      - "/ip4/127.0.0.1/udp/9093/quic-v1"
      - "/ip4/127.0.0.1/udp/9094/quic-v1"
      - "/ip4/127.0.0.1/udp/9095/quic-v1"
  cn3:
    address: "0xdD2FD4581271e230360230F9337D5c0430Bf44C0"
    quic_port: 9093
    peers:
      - "/ip4/127.0.0.1/udp/9091/quic-v1"
      - "/ip4/127.0.0.1/udp/9092/quic-v1"
      - "/ip4/127.0.0.1/udp/9094/quic-v1"
      - "/ip4/127.0.0.1/udp/9095/quic-v1"
  cn4:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9094
    peers:
      - "/ip4/127.0.0.1/udp/9091/quic-v1"
      - "/ip4/127.0.0.1/udp/9092/quic-v1"
      - "/ip4/127.0.0.1/udp/9093/quic-v1"
      - "/ip4/127.0.0.1/udp/9095/quic-v1"
  ag:
    address: "0x8626f6940E2eb28930eFb4CeF49B2d1F2C9C1199"
    quic_port: 9095
    peers:
      - "/ip4/127.0.0.1/udp/9091/quic-v1"
      - "/ip4/127.0.0.1/udp/9092/quic-v1"
      - "/ip4/127.0.0.1/udp/9093/quic-v1"
      - "/ip4/127.0.0.1/udp/9094/quic-v1"
    role:
      type: aggregator
      pubkey_write_path: "./output/pubkey.bin" # relative to this config file or absolute
      plaintext_write_path: "./output/plaintext.txt"
```
