### ISSUE TITLE
Fix enclave config contract addresses from swarm PR

### ISSUE THREAD

**Issue by ryardley** [gnosisguild/enclave#383]
```yaml
    contracts:
      enclave: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512"
      ciphernode_registry: "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
      filter_registry: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9"
```
